### ISSUE TITLE
The open task doesn't collapse when you click somewhere else in the app

### ISSUE THREAD

**Issue by jjman505** [Dunmo/Dunmo#105]
It seems like expected behavior that the task collapses if I click somewhere else. One exception might be editing the title of another task. Notably, when you click on the done button and then visit the done tasks page, the task is still open. It should be closed if marked done. Same for remove.

**Comment by heyrichardshi** [comment]
Reassigned to Jeremy. I was going to use `.blur()` to fix this, but I took a look at the code and jeremy replaced how I handled task expansion with something else, so I can't do anything about this.

**Comment by heyrichardshi** [comment]
The branch is already created btw, it's `bugfix/105`.
