### ISSUE TITLE
Calendar settings

### ISSUE THREAD

**Issue by goldmandrummer** [Dunmo/Dunmo#114]
The settings are:
- Start of Workday: The earliest time to schedule tasks
- End of Workday: The latest time to schedule tasks
- Task Granularity: The number of minutes to round each task length to
- Max Task Interval: The longest length of a task before inserting a break
- Max Time Per Task Per Day: The most hours of one task to schedule per day
- Task Break Interval: The length of breaks between tasks

**Comment by jjman505** [comment]
At some point it was on Richard's list to create the front end piece of this but it apparently fell through the cracks. It would take me only 30 minutes or so to update the code hooks.

**Comment by goldmandrummer** [comment]
Alright, I'll assign it to richard. This is a top priority thing.

**Comment by heyrichardshi** [comment]
@michael what were the settings again?
