### ISSUE TITLE
CSS red/yellow for landing page

### ISSUE THREAD

**Issue by goldmandrummer** [Dunmo/Dunmo#121]
I put a .danger and .overdue to show off having the warning for close deadlines and such

Plz pick a yellow and a red to use for the app warning colors (to be implemented by Wed.) and then throw the CSS in to apply them appropriately

**Comment by heyrichardshi** [comment]
@goldmandrummer Wait why does it say for landing page then?

**Comment by heyrichardshi** [comment]
Closed issue; duplicate of #65.
