### ISSUE TITLE
Login with Google has internal server error, doesn't login

### ISSUE THREAD

**Issue by goldmandrummer** [Dunmo/Dunmo#56]
There was an internal server error (I didn't see it before) so the login didn't go through

**Comment by goldmandrummer** [comment]
Didn't see any console logs about it though.. (on production)

**Comment by jjman505** [comment]
Might be related to permissions in Google devotees console. I'll take a look.

**Comment by jjman505** [comment]
*developers. Sorry, I'm on mobile. I'll clean up this comment later.
