### ISSUE TITLE
{60} Hotkeys for adding a task and navigation

### ISSUE THREAD

**Issue by goldmandrummer** [Dunmo/Dunmo#63]
Impact: 5, Value: 5x6x2 = 60

n, a, for opening the new task modal
t for /tasks/todo
d for /tasks/done
r for /tasks/trash
? for opening the feedback form in a new tab/window
s for /settings

This should probably be implemented using a separate module in the front end somehow to keep all the keybinding code in one place.

**Comment by jjman505** [comment]
We'll use the mousetrap library for this:
https://atmospherejs.com/mousetrap/mousetrap
https://craig.is/killing/mice
