### ISSUE TITLE
Cursor in task title field on click of +

### ISSUE THREAD

**Issue by goldmandrummer** [Dunmo/Dunmo#64]
When a user clicks the +, have the cursor automatically start in the title field

**Comment by jjman505** [comment]
I was unable to reproduce on the `develop` branch in google chrome for linux. What was your browser and system? If you accidentally double click on the plus, that will also cause the title input to lose focus.

**Comment by goldmandrummer** [comment]
I was referring to the production version, running in Chrome on OSX 

I just tried to play around with it and it looks like the first time I click + (after fresh page load I guess) the cursor appears as expected. However, every time after that, there is no cursor placed for me
