### ISSUE TITLE
Javascript on landing page does not work

### ISSUE THREAD

**Issue by heyrichardshi** [Dunmo/Dunmo#75]
Whether it's in landing .js or inline, the smooth scrolling isn't working.

**Comment by jjman505** [comment]
I don't think inline javascript works in Meteor. Any code that should be run at load time for the landing template should either go in `Template.landing.onCreated(...)` or `Template.landing.onRendered(...)`. I took a look; seems that `$('html, body').animate(...);` isn't working. No idea why. I also tried this package with no result: https://atmospherejs.com/slam310/smooth-scroll. I'm not sure what else to try.

**Comment by heyrichardshi** [comment]
I narrowed it down, and meteor just apparently hates this: `$('html, body').animate({scrollTop: $("#features").offset().top}, 500);`
